export const assets = [
  { id: 1, path: "/assets/stickers/card.png", span: 1 },
  { id: 2, path: "/assets/stickers/eyepop.png", span: 1 },
  { id: 3, path: "/assets/stickers/frown.png", span: 1 },
  { id: 4, path: "/assets/stickers/grab.png", span: 1 },
  { id: 5, path: "/assets/stickers/high.png", span: 1 },
  { id: 6, path: "/assets/stickers/span3/grossed.png", span: 3 },
  { id: 7, path: "/assets/stickers/pepe.png", span: 1 },
  { id: 8, path: "/assets/stickers/phone.png", span: 1 },
  { id: 9, path: "/assets/stickers/span2/onThePutter.png", span: 2 },
  { id: 10, path: "/assets/stickers/sad.png", span: 1 },
  { id: 11, path: "/assets/stickers/shotgun.png", span: 1 },
  { id: 12, path: "/assets/stickers/viciousness.png", span: 1 },
  { id: 13, path: "/assets/stickers/smirk.png", span: 1 },
  { id: 14, path: "/assets/stickers/shoot.png", span: 1 },
  { id: 15, path: "/assets/stickers/scream.png", span: 1 },
  { id: 16, path: "/assets/stickers/lick.png", span: 1 },
  { id: 17, path: "/assets/stickers/mock.png", span: 1 },
  { id: 18, path: "/assets/stickers/hang.png", span: 1 },
  { id: 19, path: "/assets/stickers/peacecatClr.png", span: 1 },
  { id: 20, path: "/assets/stickers/gmClean.png", span: 1 },
  { id: 21, path: "/assets/stickers/butterClean.png", span: 1 },
  { id: 22, path: "/assets/stickers/span2/moggerton.png", span: 2 },
  { id: 23, path: "/assets/stickers/nerd.png", span: 1 },
  { id: 24, path: "/assets/stickers/squidcatClr.png", span: 1 },
  { id: 25, path: "/assets/stickers/melt.png", span: 1 },
  { id: 26, path: "/assets/stickers/peacecat.png", span: 1 },
  { id: 27, path: "/assets/stickers/paleolit.png", span: 1 },
  { id: 28, path: "/assets/stickers/span2/grossedOut.png", span: 2 },
  { id: 29, path: "/assets/stickers/squidcat.png", span: 1 },
  { id: 30, path: "/assets/stickers/meltClr.png", span: 1 },
  { id: 31, path: "/assets/stickers/paleolitClr.png", span: 1 },

  { id: 32, path: "/assets/stickers/owo.png", span: 1 },
  { id: 33, path: "/assets/stickers/span3/laugh.png", span: 3 },
  {
    id: 34,
    path: "/assets/stickers/proud.png",
    span: 1,
  },
  { id: 35, path: "/assets/stickers/span2/crustyCat.png", span: 2 },
  { id: 36, path: "/assets/stickers/smoke.png", span: 1 },
  { id: 37, path: "/assets/stickers/owoClr.png", span: 1 },
  { id: 38, path: "/assets/stickers/loafClean.png", span: 1 },

  { id: 39, path: "/assets/stickers/smokeClr.png", span: 1 },
  { id: 40, path: "/assets/stickers/span2/butterMouthStick.png", span: 2 },

  { id: 41, path: "/assets/stickers/span2/butterEyeCrust.png", span: 2 },
  { id: 42, path: "/assets/stickers/span2/butterDry.png", span: 2 },
];

export const mobileAssets = [
  { id: 1, path: "/assets/stickers/card.png", span: 1 },
  { id: 2, path: "/assets/stickers/eyepop.png", span: 1 },
  { id: 3, path: "/assets/stickers/frown.png", span: 1 },
  { id: 4, path: "/assets/stickers/grab.png", span: 1 },
  { id: 5, path: "/assets/stickers/high.png", span: 1 },
  { id: 6, path: "/assets/stickers/shoot.png", span: 1 },
  { id: 7, path: "/assets/stickers/span3/grossed.png", span: 3 },
  { id: 8, path: "/assets/stickers/pepe.png", span: 1 },
  { id: 9, path: "/assets/stickers/phone.png", span: 1 },
  { id: 10, path: "/assets/stickers/mock.png", span: 1 },
  { id: 11, path: "/assets/stickers/span3/laugh.png", span: 3 },

  { id: 12, path: "/assets/stickers/sad.png", span: 1 },
  { id: 13, path: "/assets/stickers/shotgun.png", span: 1 },
  { id: 14, path: "/assets/stickers/viciousness.png", span: 1 },
  { id: 15, path: "/assets/stickers/smirk.png", span: 1 },
  { id: 16, path: "/assets/stickers/owo.png", span: 1 },
  { id: 17, path: "/assets/stickers/scream.png", span: 1 },
  { id: 18, path: "/assets/stickers/lick.png", span: 1 },
  { id: 19, path: "/assets/stickers/hang.png", span: 1 },
  { id: 20, path: "/assets/stickers/peacecatClr.png", span: 1 },
  { id: 21, path: "/assets/stickers/gmClean.png", span: 1 },
  { id: 22, path: "/assets/stickers/butterClean.png", span: 1 },
  { id: 23, path: "/assets/stickers/span2/moggerton.png", span: 2 },
  { id: 24, path: "/assets/stickers/loafClean.png", span: 2 },
  { id: 25, path: "/assets/stickers/nerd.png", span: 1 },
  { id: 26, path: "/assets/stickers/squidcatClr.png", span: 1 },
  { id: 27, path: "/assets/stickers/meltClr.png", span: 2 },
  { id: 28, path: "/assets/stickers/span2/grossedOut.png", span: 2 },
  { id: 29, path: "/assets/stickers/squidcat.png", span: 1 },

  { id: 31, path: "/assets/stickers/paleolitClr.png", span: 1 },

  { id: 32, path: "/assets/stickers/span2/onThePutter.png", span: 2 },
  {
    id: 33,
    path: "/assets/stickers/proud.png",
    span: 1,
  },
  { id: 34, path: "/assets/stickers/smoke.png", span: 1 },
  { id: 35, path: "/assets/stickers/owoClr.png", span: 1 },
  { id: 36, path: "/assets/stickers/span2/crustyCat.png", span: 2 },
  { id: 37, path: "/assets/stickers/smokeClr.png", span: 1 },

  { id: 38, path: "/assets/stickers/peacecat.png", span: 1 },
  { id: 39, path: "/assets/stickers/span2/butterMouthStick.png", span: 2 },
  { id: 40, path: "/assets/stickers/span2/butterEyeCrust.png", span: 2 },
  { id: 41, path: "/assets/stickers/melt.png", span: 1 },
  { id: 42, path: "/assets/stickers/paleolit.png", span: 1 },
  { id: 43, path: "/assets/stickers/span2/butterDry.png", span: 2 },
];
